// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOLaNYxhvfu-aZXVDhvgosS-FoSaizRs',
    appId: '1:488544495826:web:412d5713dc7236f10e650b',
    messagingSenderId: '488544495826',
    projectId: 'utm-project-case2',
    authDomain: 'utm-project-case2.firebaseapp.com',
    storageBucket: 'utm-project-case2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_DhHhq7ue7AwH5yuwcj37cHj_gMpVLo',
    appId: '1:488544495826:android:4709cf2c2ba5bceb0e650b',
    messagingSenderId: '488544495826',
    projectId: 'utm-project-case2',
    storageBucket: 'utm-project-case2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnFBqO7R24JRATU-F-nZjOzxmJiyBSQxA',
    appId: '1:488544495826:ios:1fc1f6263e8c1e490e650b',
    messagingSenderId: '488544495826',
    projectId: 'utm-project-case2',
    storageBucket: 'utm-project-case2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnFBqO7R24JRATU-F-nZjOzxmJiyBSQxA',
    appId: '1:488544495826:ios:1fc1f6263e8c1e490e650b',
    messagingSenderId: '488544495826',
    projectId: 'utm-project-case2',
    storageBucket: 'utm-project-case2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJOLaNYxhvfu-aZXVDhvgosS-FoSaizRs',
    appId: '1:488544495826:web:e4d1a8b5f6a6863f0e650b',
    messagingSenderId: '488544495826',
    projectId: 'utm-project-case2',
    authDomain: 'utm-project-case2.firebaseapp.com',
    storageBucket: 'utm-project-case2.firebasestorage.app',
  );
}
